version: '3.8'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000  # This runs the Django dev server; adjust if you're using Gunicorn
    volumes:
      - .:/usr/src/app  
    ports:
      - "8000:8000"  # Expose port 8000 for the Django app
    depends_on:
      - pgdb  # Ensure the DB container starts before Django
   

  pgdb:
    image: postgres  # Use PostgreSQL version 14
    container_name: pgdb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Load DB name from .env file
      POSTGRES_USER: ${POSTGRES_USER}  # Load DB user from .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Load DB password from .env file
