# Generated by Django 5.0.7 on 2024-09-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_to',
            new_name='valid_until',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
