# Generated by Django 5.0.7 on 2026-01-26 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.PositiveIntegerField(help_text='Maximum discount amount allowed for this coupon', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.PositiveIntegerField(help_text='Minimum cart amount required to apply this coupon', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
