# Generated by Django 5.0.7 on 2024-09-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandoffer',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productvariantoffer',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='referraloffer',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
