# Generated by Django 5.0.7 on 2024-08-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
