# Generated by Django 5.0.7 on 2024-09-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_amount',
        ),
    ]
