# Generated by Django 5.0.7 on 2024-09-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_transaction_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.CharField(default='not available', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
