# Generated by Django 5.0.7 on 2024-09-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_transaction_message_transaction_transaction_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='message',
            new_name='description',
        ),
    ]
