# Generated by Django 5.0.7 on 2025-12-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Money Added'), ('debit', 'Money Deducted'), ('null', 'No Wallet Change')], max_length=10),
        ),
    ]
