# Generated by Django 5.0.7 on 2025-12-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
