# Generated by Django 5.0.7 on 2024-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'CASH ON DELIVERY'), ('razorpay', 'razorpay'), ('wallet', 'wallet')], default='cash_on_delivery', max_length=20),
        ),
    ]
