# Generated by Django 5.0.7 on 2024-09-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_payment_status_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Deliverd', 'Deliverd')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancell', 'Cancell'), ('Deliverd', 'Deliverd')], default='Pending', max_length=20),
        ),
    ]
