# Generated by Django 5.0.7 on 2024-09-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_order_status_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Refunded', 'Refunded'), ('Failed', 'Failed'), ('On Hold', 'On Hold'), ('Awaiting Payment', 'Awaiting Payment'), ('Partially Shipped', 'Partially Shipped'), ('Pending Review', 'Pending Review')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Refunded', 'Refunded'), ('Failed', 'Failed'), ('On Hold', 'On Hold'), ('Awaiting Payment', 'Awaiting Payment'), ('Partially Shipped', 'Partially Shipped'), ('Pending Review', 'Pending Review')], default='Pending', max_length=20),
        ),
    ]
