# Generated by Django 5.0.7 on 2024-09-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
