# Generated by Django 5.0.7 on 2024-09-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_coupon_discount_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_info',
            field=models.CharField(default='Not Available', max_length=250),
        ),
    ]
