# Generated by Django 5.0.7 on 2024-09-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_coupon_info_orderitem_coupon_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='coupon_disount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
