# Generated by Django 5.0.7 on 2024-09-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orderitem_coupon_disount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='coupon_disount_price',
            new_name='coupon_discount_price',
        ),
    ]
