# Generated by Django 5.0.7 on 2024-09-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_rename_coupon_disount_price_orderitem_coupon_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'CASH ON DELIVERY'), ('razorpay', 'RAZORPAY'), ('wallet', 'WALLET')], default='', max_length=20),
        ),
    ]
