# Generated by Django 5.0.7 on 2024-09-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_orderitem_order_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancelled_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Returned', 'Returned'), ('Payment fail', 'Payment fail')], default='Order placed', max_length=20),
        ),
    ]
