# Generated by Django 5.0.7 on 2024-09-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderitem_cancelled_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cancelled_message',
            field=models.CharField(blank=True, default='Order Cancelled by Cycular-Admin', max_length=255),
        ),
    ]
