# Generated by Django 5.0.7 on 2024-09-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_orderitem_order_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Product delivery on pending', 'Product delivery on pending'), ('Product returned to near-hub', 'Product returned to near-hub'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Returned', 'Returned')], default='Order placed', max_length=50),
        ),
    ]
