# Generated by Django 5.0.7 on 2026-01-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_razorpay_in_progress',
            field=models.BooleanField(default=False, help_text='True when Razorpay payment is currently in progress'),
        ),
    ]
