# Generated by Django 5.0.7 on 2026-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Product delivery on pending', 'Product delivery on pending'), ('Product returned to near-hub', 'Product returned to near-hub'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Returned', 'Returned'), ('Pending Payment', 'Pending Payment')], default='Pending Payment', max_length=50),
        ),
    ]
