# Generated by Django 5.0.7 on 2026-01-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_alter_orderitem_order_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_razorpay_in_progress',
            field=models.BooleanField(default=False, help_text='True when Razorpay payment is currently in progress for this item'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
