# Generated by Django 5.0.7 on 2024-08-09 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand_color_size_product_status_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='color',
            name='hex_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_variants/images/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_variants/images/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_variants/images/'),
        ),
        migrations.AddField(
            model_name='size',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.color'),
        ),
        migrations.AddField(
            model_name='size',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='products.size'),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
    ]
