# Generated by Django 5.0.7 on 2024-08-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_price_productvariant_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
    ]
