# Generated by Django 5.0.7 on 2024-08-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='color',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='size',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
