# Generated by Django 5.0.7 on 2024-08-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='stock',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
