# Generated by Django 5.0.7 on 2024-08-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_size_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
