# Generated by Django 5.0.7 on 2024-08-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productvariant_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
    ]
