# Generated by Django 5.0.7 on 2024-08-24 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='products.color'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('color', 'size')},
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('name', 'color')},
        ),
    ]
