# Generated by Django 5.0.7 on 2024-08-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_color_product_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
    ]
