# Generated by Django 5.0.7 on 2024-08-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
    ]
