# Generated by Django 5.0.7 on 2024-09-04 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_size_stock_productvariant_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
