# Generated by Django 5.0.7 on 2024-09-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productvariant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
