# Generated by Django 5.0.7 on 2024-09-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_productvariant_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='offer_price',
        ),
    ]
