# Generated by Django 5.0.7 on 2024-09-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_color_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='Not selected', max_length=20, unique=True),
        ),
    ]
