# Generated by Django 5.0.7 on 2024-10-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_color_hex_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
