# Generated by Django 5.0.7 on 2024-10-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_color_hex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_variants/images/'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
